version: '3'

services:
  mysql:
      image: mariadb
      environment:
        - MYSQL_ROOT_PASSWORD=root
  phpunit:
    build:
     context: ./tests
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    entrypoint: bash -c "composer install && vendor/frozzare/wp-test-suite/bin/install-wp-tests.sh wordpress_test root root mysql latest && vendor/bin/phpunit"
